# Generated by Django 6.0.3 on 2026-04-27 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_account_request_usernames(apps, schema_editor):
    AccountRequest = apps.get_model('inventory', 'AccountRequest')
    used = set()

    for account_request in AccountRequest.objects.all().order_by('id'):
        base_username = (account_request.full_name or '').strip() or account_request.email.split('@')[0]
        candidate = base_username
        suffix = 1
        while not candidate or candidate.lower() in used:
            candidate = f"{base_username}-{suffix}" if base_username else f"user-{account_request.id}-{suffix}"
            suffix += 1
        account_request.username = candidate
        account_request.save(update_fields=['username'])
        used.add(candidate.lower())


def create_user_access_rows(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    UserAccess = apps.get_model('inventory', 'UserAccess')

    for user in User.objects.all().iterator():
        UserAccess.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_accountrequest_invitecode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='accountrequest',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.RunPython(backfill_account_request_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='accountrequest',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_user_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_user_access_rows, migrations.RunPython.noop),
    ]
