# Generated by Django 4.2 on 2026-05-04 16:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone
import inventory.models


def create_initial_stock_in_records(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    StockIn = apps.get_model('inventory', 'StockIn')
    stock_ins = [
        StockIn(
            product_id=product.id,
            quantity=product.stock_quantity,
            received_at=timezone.now(),
            notes='Existing stock balance before stock-in tracking was enabled.',
        )
        for product in Product.objects.filter(stock_quantity__gt=0)
    ]
    StockIn.objects.bulk_create(stock_ins)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_auth_overhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_threshold',
            field=models.PositiveIntegerField(default=inventory.models.default_reorder_threshold),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='inventory.product')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-received_at', '-id'),
            },
        ),
        migrations.RunPython(create_initial_stock_in_records, migrations.RunPython.noop),
    ]
